# Generated by Django 5.0.4 on 2024-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
